minversion = "4"
env_list = ["py313", "py312", "py311"]
isolated_build = true
skip_missing_interpreters = true

[env_run_base]
allowlist_externals = ["pytest"]
# TODO: only install ci in ci…, maybe using the gh-actions thing?
dependency_groups = ["ci", "tests", "parity-tests"]
commands = [
    [
        'pytest',
        "tests",
        "--basetemp",
        "{envtmpdir}",
        { replace = "posargs", extend = true },
    ],
]


[gh-actions]
python = """
3.11: py311
3.12: py312
3.13: py313"""
